name: yokg

services:
  postgres:
    image: postgres:18.1-trixie
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      POSTGRES_DB: ${POSTGRES_DB:-yokg}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./.docker/postgres:/var/lib/postgresql
    networks:
      - yokg
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5

  age:
    image: apache/age:release_PG17_1.6.0
    ports:
      - ${AGE_PORT:-5455}:5432
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      POSTGRES_DB: ${AGE_DB:-graph}
      POSTGRES_USER: ${AGE_USER:-postgres}
      POSTGRES_PASSWORD: ${AGE_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./.docker/age:/var/lib/postgresql
    networks:
      - yokg
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${AGE_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5

  pgvector:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    ports:
      - ${PGVECTOR_PORT:-5487}:5432
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      POSTGRES_DB: ${PGVECTOR_DB:-graph}
      POSTGRES_USER: ${PGVECTOR_USER:-postgres}
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./.docker/pgvector:/var/lib/postgresql
    networks:
      - yokg
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${PGVECTOR_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4-bookworm
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ./.docker/redis/data:/data
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - yokg
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.76
    ports:
      - ${OBJECT_STORAGE_SELF_HOSTED_VENDOR_API_PORT-:9000}:9000
      - ${OBJECT_STORAGE_SELF_HOSTED_VENDOR_CONSOLE_PORT-:9001}:9001
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      RUSTFS_ACCESS_KEY: ${OBJECT_STORAGE_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${OBJECT_STORAGE_SECRET_KEY}
    volumes:
      - ./.docker/rustfs/data:/data
    restart: unless-stopped
    networks:
      - yokg
    healthcheck:
      test:
        [
          'CMD',
          'sh',
          '-c',
          'curl -f http://localhost:9000/health && curl -f http://localhost:9001/rustfs/console/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  yokg:
    driver: bridge
